### ISSUE TITLE
Roadmap for V3 and V4

### ISSUE THREAD

**Issue by Maks3w** [zendframework/zend-inputfilter#39]
Proposal of roadmap for next major versions.

V3:
V3 should silently fail if any deprecation feature is used. i.e. No file removal/rename is allowed.

- [ ] Deprecate Continue If Empty & AllowEmpty
- [ ] Let Input if is validating over an unknown value (not-set) or know value.
- [ ] Leverage InputFilter from apply complex rules for to determinate if input is valid/invalid
- [ ] Add a resetX method for clear the class state

V4:
V4 does not (currently) restrict any bc break type.

- [ ] Remove deprecated features
- [ ] Fix class inheritance (subclasses must follow the api contract set by the parent) Affected: CollectionInputFilter, ArrayInput and FileInput
- [ ] Make classes stateless
- [ ] Adapted for zend-validator v3

**Comment by bakura10** [comment]
Hi,

We shoudl also have a look at the refactor I did: https://github.com/zendframework/zend-inputfilter/issues/13

It simplified A LOT of things regarding to continue/allow_empty, stateless, refactored collection input filter... and a lot of other things. I did that a lot of time ago so I don't exactly remember, but this refactor mostly answered to most of the problems you are referring to :).

I will start working again on this, but first we'll need to have the stateless zend-validator and zend-filter.

**Comment by RalfEggert** [comment]
What is the status for the stateless input filters?

**Comment by weierophinney** [comment]
@RalfEggert Still in planning stages, though @bakura10 has done significant work on a fork he's maintaining. (I've asked him to document usage so I can actually evaluate the changes and the migration/usage impact.)

**Comment by bakura10** [comment]
Stateless input filter can only be done once we have stateless validators :).

**Comment by xorock** [comment]
What do You think of renaming this component to something more accurate? I dont know, maybe inputparser?
Inputfilter name is very confusing. What it does is filtration and validation. For someone who does not know Zend libraries it is hard to find the difference between filter and inputfilter.

**Comment by thexpand** [comment]
@bakura10 @weierophinney What is the status of this? Is it being abandoned in favor of the eventually up-coming `zend-datavalidator` in the future?

**Comment by froschdesign** [comment]
@thexpand 
> Is it being abandoned in favor of the eventually up-coming `zend-datavalidator` in the future?

Please keep in mind that the input-filter is doing something more than validation for values. The [`zend-datavalidator`](https://github.com/weierophinney/zend-datavalidator) will replace zend-validator and not zend-inputfilter.

**Comment by weierophinney** [comment]
That's actually still to be determined. There's a fair amount of cross over
in how validators and inputs report errors, and my current work has been
around adding the input/data set functionality to the new component.

**Comment by weierophinney** [comment]
This repository has been closed and moved to laminas/laminas-inputfilter; a new issue has been opened at https://github.com/laminas/laminas-inputfilter/issues/11.
